// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type JobApplication struct {
	ID          string           `json:"id"`
	Title       string           `json:"title"`
	Company     string           `json:"company"`
	AppliedDate pgtype.Timestamp `json:"applied_date"`
	UserID      string           `json:"user_id"`
	LabelID     pgtype.Text      `json:"label_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Label struct {
	ID     string `json:"id"`
	Title  string `json:"title"`
	UserID string `json:"user_id"`
}

type MagicLink struct {
	ID        string           `json:"id"`
	Email     string           `json:"email"`
	Token     string           `json:"token"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

type Session struct {
	ID        string           `json:"id"`
	UserID    string           `json:"user_id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

type User struct {
	ID        string           `json:"id"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
