// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MagicLink struct {
	ID        string           `json:"id"`
	Email     string           `json:"email"`
	Token     string           `json:"token"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

type Session struct {
	ID        string           `json:"id"`
	UserID    string           `json:"user_id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

type User struct {
	ID        string           `json:"id"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
